services:

  flow2:
    build:
      context: .
      target: runtime
    image: flow2:latest
    ports:
      - "80" # nginx will proxy requests, no need to expose to host
    volumes:
      - flow2-media-vol:/data/media
    networks:
      - my-network
    env_file:
      - ./env/flow2/.env-local

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/conf.d:/etc/nginx/conf.d
      - flow2-media-vol:/usr/share/nginx/media
    env_file:
      - ./env/nginx/.env-local
    depends_on:
      - flow2
    networks:
      - my-network

  mongosrv:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - flow2-db-vol:/data/db
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - my-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongohiimadbadmin
      - MONGO_INITDB_ROOT_PASSWORD=mongoimdoesntscaredofnobody

networks:
  my-network:

volumes:
  flow2-db-vol:
    external: true
  flow2-media-vol:
    external: true
