services:

  flow2:
    build:
      context: .
      target: runtime
    image: flow2:latest
    ports:
      - "80:80"
    volumes:
      - flow2-media-vol:/data/media
    networks:
      - my-network
    environment:
      - DEVELOPMENT=false
      - ADMIN_SESSION_COOKIE=sesh
      - ADMIN_USERNAME=hiimanadmin
      - ADMIN_PASSWORD=imdoesntscaredofnobody
      - DIGEST_SALT=saltnpeppawantutopushitrealgood
      - DB_CONNECTION_STRING=mongodb://mongohiimadbadmin:mongoimdoesntscaredofnobody@mongosrv:27017/flow2?authSource=admin
      - DB_NAME=flow2
      - MEDIA_DIRECTORY_PATH=/data/media

  mongosrv:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - flow2-db-vol:/data/db
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - my-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongohiimadbadmin
      - MONGO_INITDB_ROOT_PASSWORD=mongoimdoesntscaredofnobody

networks:
  my-network:

volumes:
  flow2-db-vol:
    external: true
  flow2-media-vol:
    external: true
