services:

  flow2:
    build:
      context: .
      target: runtime
    #image: flow2:latest
    ports:
      - "8080:8080"
    networks:
      - my-network
    environment:
      - DEVELOPMENT=false
      - ADMIN_SESSION_COOKIE=sesh
      - ADMIN_USERNAME=hiimanadmin
      - ADMIN_PASSWORD=imdoesntscaredofnobody
      - DIGEST_SALT=saltnpeppawantutopushitrealgood
      - DB_CONNECTION_STRING=mongodb://mongosrv:27017
      - DB_NAME=flow2

  mongosrv:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - flow2-vol:/data/db
    networks:
      - my-network

networks:
  my-network:

volumes:
  flow2-vol:
    external: true
