ktor:
    development: "$DEVELOPMENT_MODE:false"
    application:
        modules:
            - com.flow2.ApplicationKt.module
    deployment:
        port: "$HTTP_PORT:80"

app:
    schemeDomainPort: "$SCHEME_DOMAIN_PORT:http://localhost:8080"
    adminAuth:
        sessionCookie: "$ADMIN_SESSION_COOKIE:sesh"
        username: "$ADMIN_USERNAME:admin"
        password: "$ADMIN_PASSWORD:password"
        digestSalt: "$DIGEST_SALT:saltnpepper"
    db:
        connectionString: "$DB_CONNECTION_STRING:mongodb://localhost:27017"
        dbName: "$DB_NAME:flow2"

    media:
        directoryPath: "$MEDIA_DIRECTORY_PATH:src/main/resources/media"


